#!/bin/sh
# AISPM host agent installer (Linux, macOS).
#
# Two modes, same script:
#   package   — run from the unzipped installer package; reads installer.conf + bootstrap.token
#               sitting next to this script.
#   one-liner — curl -fsSL <platform>/aispm/api/v1/agent/install.sh \
#                 | sh -s -- --platform-url https://platform.example --token-file ./bootstrap.token
#
# It detects the OS/arch, checks the prerequisites, lays out the install directory, downloads the
# binary and the configuration for the resolved release (SHA256 verified), gates on the agent's own
# preflight, enrols the host, and prints the exact command to run it.
#
# Exit codes. Below 10 the installer itself failed; 10 and above are the agent's frozen enrollment
# codes, passed through unchanged so the number an operator reports means one thing only
# (see docs/installer-distribution-plan.md §2c):
#   0  installed (and enrolled)
#   1  unexpected failure
#   2  usage error
#   3  this OS/arch is not supported, or no binary is published for it yet
#   4  a prerequisite is missing
#   5  not running as root
#   6  the platform is not reachable
#   7  download or checksum failure
#   8  the agent's preflight refused this host
#   10 bootstrap token invalid, expired, revoked or already used
#   11 platform unreachable from the agent
#   12 agent configuration error
#   13 platform reachable but unable to enrol
set -eu

EX_OK=0; EX_FAIL=1; EX_USAGE=2; EX_UNSUPPORTED=3; EX_PREREQ=4
EX_PRIVILEGE=5; EX_PLATFORM=6; EX_DOWNLOAD=7; EX_PREFLIGHT=8

# Defaults. --manifest-url (or installer.conf) overrides the whole resolution chain.
RELEASES_OWNER="${AISPM_RELEASES_OWNER:-illuminait-io}"
RELEASES_REPO="aispm-agent-releases"
DEFAULT_CHANNEL="stable"
INSTALL_ROOT_DEFAULT="/opt/IlluminaIT"
AGENT_BIN="aispm-agent"
# Marker dropped before the first mutation and removed on success: a re-run knows it is resuming.
INCOMPLETE_MARKER=".install-incomplete"
PING_PATH="/aispm/api/v1/agent/ping"
MIN_FREE_KB=262144 # 256 MiB: binary + config + room for the first logs

platform_url=""; token=""; token_file=""; version=""; channel=""
manifest_url=""; install_dir=""; re_enroll=0

say()  { printf '%s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { code="$1"; shift; printf 'error: %s\n' "$*" >&2; exit "$code"; }

usage() {
	cat <<'USAGE'
Usage: install.sh [options]

  --platform-url URL   AISPM platform base URL (https). Required unless installer.conf provides it.
  --token TOKEN        single-use bootstrap token. Prefer --token-file: an argv token is visible
                       in `ps` and in the shell history.
  --token-file PATH    file holding the bootstrap token (default: ./bootstrap.token when present)
  --version X.Y.Z      install this exact agent version instead of the channel's current one
  --channel NAME       release channel to follow (default: stable)
  --manifest-url URL   resolve the release from this manifest, bypassing the channel
  --install-dir PATH   install root (default: /opt/IlluminaIT)
  --re-enroll          discard the stored credential and enrol again (needs a fresh token)
  -h, --help           this help
USAGE
}

while [ $# -gt 0 ]; do
	case "$1" in
	--platform-url) platform_url="${2:-}"; shift 2 ;;
	--token)        token="${2:-}"; shift 2 ;;
	--token-file)   token_file="${2:-}"; shift 2 ;;
	--version)      version="${2:-}"; shift 2 ;;
	--channel)      channel="${2:-}"; shift 2 ;;
	--manifest-url) manifest_url="${2:-}"; shift 2 ;;
	--install-dir)  install_dir="${2:-}"; shift 2 ;;
	--re-enroll)    re_enroll=1; shift ;;
	-h|--help)      usage; exit $EX_OK ;;
	*)              usage >&2; die $EX_USAGE "unknown option: $1" ;;
	esac
done

# ---------------------------------------------------------------- package mode
# installer.conf and bootstrap.token travel with the script in the zip. Anything passed on the
# command line wins, so the one-liner and the package share this code path.
script_dir() {
	# $0 is not a path when piped from curl; fall back to the working directory.
	case "${0:-}" in
	-|sh|bash|/dev/fd/*|"") printf '%s' "$PWD" ;;
	*) d=$(dirname -- "$0") 2>/dev/null || d="$PWD"; (cd -- "$d" 2>/dev/null && pwd) || printf '%s' "$PWD" ;;
	esac
}
HERE=$(script_dir)

if [ -f "$HERE/installer.conf" ]; then
	say "using $HERE/installer.conf"
	# Only known keys are read, and never with eval: the file is generated by the platform but
	# still travels on a user's disk.
	conf_get() { sed -n 's/^[[:space:]]*'"$1"'[[:space:]]*=[[:space:]]*//p' "$HERE/installer.conf" | tr -d '\r' | head -1; }
	[ -n "$platform_url" ] || platform_url=$(conf_get platformUrl)
	[ -n "$channel" ]      || channel=$(conf_get channel)
	[ -n "$version" ]      || version=$(conf_get agentVersion)
	[ -n "$manifest_url" ] || manifest_url=$(conf_get manifestUrl)
fi
if [ -z "$token" ] && [ -z "$token_file" ] && [ -f "$HERE/bootstrap.token" ]; then
	token_file="$HERE/bootstrap.token"
fi

[ -n "$channel" ] || channel="$DEFAULT_CHANNEL"
[ -n "$install_dir" ] || install_dir="$INSTALL_ROOT_DEFAULT"
[ -n "$platform_url" ] || { usage >&2; die $EX_USAGE "--platform-url is required (or provide installer.conf)"; }
case "$platform_url" in
https://*) ;;
*) die $EX_USAGE "--platform-url must be an https URL, got '$platform_url'" ;;
esac
platform_url=$(printf '%s' "$platform_url" | sed 's:/*$::')

# --------------------------------------------------------------- 1. os / arch
step "Detecting the operating system and architecture"
uname_s=$(uname -s); uname_m=$(uname -m)
case "$uname_s" in
Linux)  os="linux" ;;
Darwin) os="darwin" ;;
*) die $EX_UNSUPPORTED "unsupported operating system '$uname_s' (this installer covers Linux and macOS; use install.ps1 on Windows)" ;;
esac
case "$uname_m" in
x86_64|amd64) arch="amd64" ;;
aarch64|arm64) arch="arm64" ;;
*) die $EX_UNSUPPORTED "unsupported architecture '$uname_m' (the agent is published for amd64 and arm64)" ;;
esac
say "  $os/$arch"

# ----------------------------------------------------- 2. prerequisites, privileges
step "Checking the prerequisites"
need() { command -v "$1" >/dev/null 2>&1 || die $EX_PREREQ "'$1' is required but not installed ($2)"; }
need curl "install curl, or fetch the package on another machine and copy it over"
need tar  "install tar (GNU tar or bsdtar)"

# sha256: coreutils on Linux, shasum on macOS. The checksum is not optional — it is the only
# integrity check on a binary fetched over the public internet.
if command -v sha256sum >/dev/null 2>&1; then
	sha256_of() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
	sha256_of() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
	die $EX_PREREQ "no sha256 tool found (install coreutils for sha256sum, or use shasum)"
fi

# Root is required, not advisory: the agent's own preflight treats missing elevation as a FATAL
# check, so a non-root install would produce an agent that cannot start.
if [ "$(id -u)" -ne 0 ]; then
	die $EX_PRIVILEGE "this installer must run as root (the agent needs root to observe processes and traffic): re-run with 'sudo $0 $*'"
fi

parent_dir="$install_dir"
while [ ! -d "$parent_dir" ] && [ "$parent_dir" != "/" ]; do parent_dir=$(dirname -- "$parent_dir"); done
free_kb=$(df -Pk "$parent_dir" 2>/dev/null | awk 'NR==2 {print $4}' || echo 0)
case "$free_kb" in
''|*[!0-9]*) warn "could not determine the free space on $parent_dir" ;;
*) [ "$free_kb" -ge "$MIN_FREE_KB" ] || die $EX_PREREQ "not enough free space on $parent_dir: $((free_kb/1024)) MiB available, $((MIN_FREE_KB/1024)) MiB required" ;;
esac
say "  root privileges, curl, tar, sha256, free space: ok"

step "Checking that the platform is reachable"
# A strict 200 on the liveness endpoint. Any other answer means the URL reaches something that
# is not the agent API — typically a reverse proxy or load balancer that does not route
# /aispm/api/v1/agent/ — which is exactly the misconfiguration worth catching before enrolling.
# curl already writes 000 when it never got a response; do not append a second fallback, or the
# "unreachable" branch below stops matching and the operator gets the wrong guidance.
ping_code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "$platform_url$PING_PATH" 2>/dev/null) || true
[ -n "$ping_code" ] || ping_code="000"
if [ "$ping_code" = "200" ]; then
	say "  $platform_url$PING_PATH -> 200"
elif [ "$ping_code" = "000" ]; then
	die $EX_PLATFORM "cannot reach $platform_url: check the URL, DNS, egress rules and TLS trust from this host (set HTTPS_PROXY if this host needs a proxy)"
else
	die $EX_PLATFORM "$platform_url$PING_PATH answered HTTP $ping_code, not 200: the URL does not reach the agent API (wrong host, or a proxy that does not route /aispm/api/v1/agent/)"
fi

# ------------------------------------------------------------- 3. release resolution
# Minimal JSON readers. The manifest and channel files are produced by our own release CI, and
# these only ever read string fields, one level deep — enough to avoid requiring jq on a host
# that may have nothing installed.
# '|' is the substitution delimiter on purpose: keys include "linux/amd64", and a '/' delimiter
# would turn the platform key into a broken sed expression (and then into a misleading
# "not published for this platform" error).
json_string() { # <json> <key>
	printf '%s' "$1" | tr -d '\n\t' | sed -n 's|.*"'"$2"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*|\1|p' | head -1
}
json_object() { # <json> <key> -> the {...} value of that key
	printf '%s' "$1" | tr -d '\n\t' | sed -n 's|.*"'"$2"'"[[:space:]]*:[[:space:]]*{\([^}]*\)}.*|\1|p' | head -1
}

fetch() { # <url> -> body on stdout
	curl -fsSL --max-time 60 "$1" || return 1
}

step "Resolving the release"
if [ -z "$manifest_url" ]; then
	if [ -n "$version" ]; then
		manifest_url="https://github.com/$RELEASES_OWNER/$RELEASES_REPO/releases/download/v$version/manifest.json"
	else
		# One flat file per channel on the distribution repo's main branch: channel.json for
		# stable, channel-<name>.json for any other. AISPM_CHANNEL_URL overrides it for internal
		# mirrors and for testing this script.
		if [ "$channel" = "$DEFAULT_CHANNEL" ]; then channel_file="channel.json"; else channel_file="channel-$channel.json"; fi
		channel_url="${AISPM_CHANNEL_URL:-https://raw.githubusercontent.com/$RELEASES_OWNER/$RELEASES_REPO/main/$channel_file}"
		say "  channel '$channel' via $channel_url"
		channel_json=$(fetch "$channel_url") || die $EX_UNSUPPORTED "no such release channel '$channel': $channel_url is not published"
		version=$(json_string "$channel_json" version)
		manifest_url=$(json_string "$channel_json" manifestUrl)
		# A bootstrapped channel file carries nulls until the first release is cut; nulls are not
		# quoted strings, so both reads come back empty.
		[ -n "$manifest_url" ] || die $EX_FAIL "release channel '$channel' has no published release yet (no manifest in $channel_url) — pin a version with --version, or wait for the first release"
	fi
fi

manifest=$(fetch "$manifest_url") || die $EX_DOWNLOAD "cannot fetch the manifest $manifest_url"
man_version=$(json_string "$manifest" version)
[ -n "$man_version" ] || die $EX_FAIL "the manifest at $manifest_url has no version field"
[ -z "$version" ] || [ "$version" = "$man_version" ] || warn "requested version $version, manifest describes $man_version"
version="$man_version"
say "  agent $version (channel ${channel})"

# Fail before downloading anything if this platform was never published: the manifest is the
# authority on what exists, which is the whole reason resolution goes through it.
artifact=$(json_object "$manifest" "$os/$arch")
[ -n "$artifact" ] || die $EX_UNSUPPORTED "no agent binary published for $os/$arch in release $version — the manifest lists no such artifact (ask for this platform, or install on a supported one)"
bin_url=$(json_string "{$artifact}" url); bin_sha=$(json_string "{$artifact}" sha256)
[ -n "$bin_url" ] && [ -n "$bin_sha" ] || die $EX_FAIL "the manifest entry for $os/$arch is missing its url or sha256"

# The configuration is NOT optional: the agent has no compiled-in catalogues, so an empty
# config/ yields an agent that starts, warns, and classifies nothing.
config_artifact=$(json_object "$manifest" config)
[ -n "$config_artifact" ] || die $EX_FAIL "release $version publishes no configuration bundle; the agent cannot classify anything without it"
cfg_url=$(json_string "{$config_artifact}" url); cfg_sha=$(json_string "{$config_artifact}" sha256)
[ -n "$cfg_url" ] && [ -n "$cfg_sha" ] || die $EX_FAIL "the manifest's config entry is missing its url or sha256"

# ------------------------------------------------------------ 4. directory layout
step "Preparing $install_dir"
config_dir="$install_dir/config"
logs_dir="$install_dir/logs"
mkdir -p "$install_dir" "$config_dir" "$logs_dir" || die $EX_FAIL "cannot create $install_dir"
[ -w "$install_dir" ] || die $EX_FAIL "$install_dir is not writable"
# The config dir stays writable for the agent itself: credential.json, host.json, the identity
# salt and the keylog cache all live there.
chmod 0755 "$install_dir" "$logs_dir"
chmod 0700 "$config_dir"
: > "$config_dir/$INCOMPLETE_MARKER"
say "  $install_dir/$AGENT_BIN, $config_dir, $logs_dir"

tmp=$(mktemp -d 2>/dev/null || mktemp -d -t aispm-install)
cleanup() { rm -rf "$tmp"; }
trap cleanup EXIT INT TERM

verify() { # <file> <expected sha256> <label>
	got=$(sha256_of "$1")
	[ "$got" = "$2" ] || die $EX_DOWNLOAD "$3 failed its checksum: expected $2, got $got (corrupted download, or a tampered artifact — do not run it)"
}

# --------------------------------------------------------------- 5. binary + config
step "Downloading the agent"
say "  $bin_url"
curl -fsSL --max-time 600 -o "$tmp/$AGENT_BIN" "$bin_url" || die $EX_DOWNLOAD "cannot download the agent binary from $bin_url"
verify "$tmp/$AGENT_BIN" "$bin_sha" "the agent binary"
chmod 0755 "$tmp/$AGENT_BIN"
mv -f "$tmp/$AGENT_BIN" "$install_dir/$AGENT_BIN"
say "  installed $install_dir/$AGENT_BIN (sha256 verified)"

step "Installing the configuration"
say "  $cfg_url"
curl -fsSL --max-time 600 -o "$tmp/config.tar.gz" "$cfg_url" || die $EX_DOWNLOAD "cannot download the configuration bundle from $cfg_url"
verify "$tmp/config.tar.gz" "$cfg_sha" "the configuration bundle"
mkdir -p "$tmp/config"
tar -xzf "$tmp/config.tar.gz" -C "$tmp/config" || die $EX_FAIL "cannot unpack the configuration bundle"
# Default catalogues are versioned with the binary and always refreshed; anything an operator
# may have edited (agent.yaml, *.custom.yaml) is installed only when absent.
for f in "$tmp"/config/*; do
	[ -f "$f" ] || continue
	base=$(basename -- "$f")
	# Skip AppleDouble side files: a bundle ever packed on macOS carries ._* siblings, and
	# copying them into config/ leaves junk the agent would scan (deploy-windows.ps1 filters
	# them for the same reason).
	case "$base" in ._*) continue ;; esac
	case "$base" in
	*.default.yaml) cp -f "$f" "$config_dir/$base" ;;
	# A bundled agent.yaml is installed as a REFERENCE only: the live one is written below with
	# this platform's URL and token path, and letting the bundle land on agent.yaml would make
	# that step think an operator had already configured the agent.
	agent.yaml|agent.yaml.example) cp -f "$f" "$config_dir/agent.yaml.example" ;;
	*) [ -f "$config_dir/$base" ] || cp "$f" "$config_dir/$base" ;;
	esac
done
say "  catalogues installed in $config_dir"

# ------------------------------------------------------------------- 6. token
token_path="$config_dir/bootstrap.token"
if [ -n "$token_file" ]; then
	[ -f "$token_file" ] || die $EX_USAGE "--token-file '$token_file' does not exist"
	cp "$token_file" "$token_path"
elif [ -n "$token" ]; then
	printf '%s\n' "$token" > "$token_path"
fi
[ ! -f "$token_path" ] || chmod 0600 "$token_path"

# agent.yaml carries the two settings the agent needs to enrol. Written only when absent, so a
# re-run never clobbers an operator's edits.
if [ ! -f "$config_dir/agent.yaml" ]; then
	cat > "$config_dir/agent.yaml" <<YAML
# Written by install.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — agent $version
platform:
  url: $platform_url
  bootstrap_token_file: $token_path
YAML
	chmod 0640 "$config_dir/agent.yaml"
	say "  wrote $config_dir/agent.yaml"
else
	say "  kept the existing $config_dir/agent.yaml"
	grep -q "$platform_url" "$config_dir/agent.yaml" 2>/dev/null || \
		warn "the existing agent.yaml does not mention $platform_url — check platform.url and platform.bootstrap_token_file"
fi

# --------------------------------------------------------------- 7. preflight + enroll
if [ "$re_enroll" -eq 1 ] && [ -f "$config_dir/credential.json" ]; then
	say "  --re-enroll: discarding the stored credential (the platform revokes its key on the next enrollment)"
	rm -f "$config_dir/credential.json"
fi

step "Running the agent's preflight"
# -preflight-save also persists host.json, which the enrollment below reads to record the cloud
# environment. Without it every agent would enrol as on-premise.
set +e
"$install_dir/$AGENT_BIN" -preflight-save -config "$config_dir"
pf_code=$?
set -e
[ "$pf_code" -eq 0 ] || die $EX_PREFLIGHT "the agent's preflight refused this host (see the failed checks and their remediation above)"

step "Enrolling with $platform_url"
set +e
"$install_dir/$AGENT_BIN" -enroll-only -config "$config_dir"
enroll_code=$?
set -e
if [ "$enroll_code" -ne 0 ]; then
	case "$enroll_code" in
	10) say ""; say "The bootstrap token was rejected. Issue a new one from Agents Fleet -> Deploy agent"
	    say "and re-run this installer; tokens are single-use and short-lived." ;;
	11) say ""; say "The agent could not reach $platform_url even though this installer could."
	    say "Check egress rules and TLS trust for the agent's own process, and HTTPS_PROXY if this host needs a proxy." ;;
	12) say ""; say "The agent rejected its configuration. Check platform.url and platform.bootstrap_token_file"
	    say "in $config_dir/agent.yaml." ;;
	13) say ""; say "The platform answered but cannot enrol this host — usually its agent signing keys"
	    say "are not provisioned yet. Ask the platform administrator, then re-run this installer." ;;
	esac
	exit "$enroll_code"
fi

rm -f "$config_dir/$INCOMPLETE_MARKER"

# ------------------------------------------------------------------ 8. how to run
cat <<FINAL

==> Installed: aispm-agent $version in $install_dir

Start the agent:

  sudo $install_dir/$AGENT_BIN -config $config_dir \\
       -logging-output $logs_dir/agent.log -logging-truncate=false

  (-logging-truncate=false keeps the log across restarts; the default empties it at startup.
   The agent log is not rotated — watch $logs_dir.)

Stop it CLEANLY — Ctrl+C, or:

  sudo kill -TERM \$(pgrep -f '$AGENT_BIN -config')

  NEVER 'kill -9'. The agent must unhook the processes it instrumented; killing it hard can
  crash or freeze the applications it was watching.

Logs:       $logs_dir
Config:     $config_dir   (agent.yaml, catalogues, credential.json)
FINAL
exit $EX_OK
